### ISSUE TITLE
Migrate to {cli} for user messages and errors

### ISSUE THREAD

**Issue by JosiahParry** [R-ArcGIS/arcgis#2]
`httr2` already imports `{cli}` and httr2 is a hard dependency. Adding cli as a dependency will not increase the size of any of the packages so we may as well take advantage of it.

## Tasks 

- [ ] Create issue in arcgislayers
  - [ ] replace all occurrences of `message()`, `warning()`, `stop()` and `stopifnot()` with an appropriate cli function.
- [ ] Create issue in arcgisutils
  - [ ] replace all occurrences of `message()`, `warning()`, `stop()` and `stopifnot()` with an appropriate cli function.
